#!/bin/bash

echo -n "Enter your device name : "
read device

while [ "$choice" != 0 ]; do
	echo "Enter 1 to get ip address"
	echo "Enter 2 to get mac address"
	echo "Enter 3 to test network status"
	echo "Enter 4 to get disk status"
	echo "Enter 0 to quite"
	echo -n "Enter your choice : "
	read choice
	echo ""
	if [ "$choice" = 1 ]; then
	ip=$(ip addr show "$device" |grep -w inet | awk -F" " '{ print $2 }')
	echo "$device ip : $ip"
	elif [ "$choice" = 2 ]; then
	mac=$(ip addr show "$device" |grep -w ether | awk -F" " '{ print $2 }')
	echo "$device ip : $mac"
	elif [ "$choice" = 3 ]; then
	echo -n "Please enter a website or ip to ping : "
	read site
	echo "Testing $site network ,pinging..."
	ststus=$(ping -c 10 "$site" | grep -w packets | awk -F"," '{ print $3 }')
	echo "Network Srength : $ststus"
	elif [ "$choice" = 4 ]; then
	mem=$(free -m)
	echo "Device data : "
	echo "$mem"
	elif [ "$choice" = 0 ]; then
	echo "thank you for choosing us"
	else 
		echo "This is  not an option , try again"
	fi


done
